on: [push]
jobs:
  build-offline-doc:
    runs-on: ubuntu-latest
    container: antonkrug/documentation-builders-ng:0fa69ed
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: cd source/main && make html
      - run: cd source/main && make linkcheck
      - run: cd source/main && make html && cd ../../ && zip -r offline-doc-archive.zip ./build/main 
      - run: ls -la
      - uses: ncipollo/release-action@v1
        with:
          name: "Offline doc"
          artifacts: "offline-doc-archive.zip"
          body: "Snapshot offline doc"
          token: ${{ secrets.GITHUB_TOKEN }}