on: [push]
jobs:
  build-offline-doc:
    runs-on: ubuntu-latest
    container: antonkrug/documentation-builders-ng:0fa69ed
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: cd source/main && make html
      